myshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import MyAccountSignupView
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounts/signup/', MyAccountSignupView.as_view(), name='account-signup'),
    re_path(r'^accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('admin-panel/', include(('adminpanel.urls', 'adminpanel'), namespace='adminpanel')),
    path('maps/', MapsView.as_view(), name='maps'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path, re_path
from .views import *

urlpatterns = [
    re_path(r'', ProductsFilterView.as_view(), name='products'),
    
]

users/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.contrib.auth.views import *
from .views import *



urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login-validation/', LoginValidationView.as_view(), name='login-validation'),
    path('registration-validation/', RegistrationValidationView.as_view(), name='registration-validation'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),


    path('confirm-email/', TemplateView.as_view(template_name='registration/confirm_email.html'), name='confirm-email'), # user will see this page after registration
    path('email-verification/<uidb64>/<token>', EmailVerificationView.as_view(), name='email-verification'), #link that user gets in email
    path('invalid_email', TemplateView.as_view(template_name='registration/invalid_email.html'), name='invalid-email'),

    path('admin-panel/', AdminPanelView.as_view(), name='admin-panel'),
]

products/models.py
from mptt.models import MPTTModel, TreeForeignKey
from PIL import Image as pil_image
import uuid

from django.db import models
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

from utils.models import DateTimeMixin, HiddenDeletedMixin




class Category(MPTTModel):
    name = models.CharField(max_length=128, unique=True)
    parent = TreeForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='children')
    attributes = models.ManyToManyField('Attribute', through='CategoryAttribute')

    class MPTTMeta:
        order_insertion_by = ['name']
        
    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    @property
    def path(self):
        path = '/' + self.name.lower() + '/'
        while self.parent:
            path = '/' + self.parent.name.lower() + path
            self = self.parent
        return path

    def __str__(self):
        return f'{self.id} - {self.name}'


class Product(models.Model):
    name = models.CharField(max_length=255)
    category = TreeForeignKey(Category, on_delete=models.PROTECT)
    short_desc = models.CharField(max_length=255, blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    brand = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.id} - {self.name} - {self.category.name}'


class StockKeepingUnit(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    category_attributes = models.ManyToManyField('CategoryAttribute', through='SKUCategoryAttribute')
    recommended_retail_price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    sale_price = models.DecimalField(default=0, max_digits=10, decimal_places=2)
    slug = models.SlugField(null=True, blank=True)
    in_stock = models.PositiveSmallIntegerField(default=0)
    on_sale = models.BooleanField(default=False)
    web_id = models.UUIDField(default=uuid.uuid4, editable=False, unique=True, max_length=16)

    def __str__(self):
        return f'{self.id} - {self.product.name}'

class CategoryAttribute(models.Model):
    
    FILTER_CHOICES = [
    ('range', 'range'), 
    ('single', 'single'), 
    ('multi', 'multi')
    ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    attribute = models.ForeignKey('Attribute', on_delete=models.CASCADE)
    show_on_tile = models.BooleanField(default=True)
    show_in_description = models.BooleanField(default=True)
    units = models.CharField(max_length=128, blank=True, null=True)

    filter_type = models.CharField(max_length=64, choices=FILTER_CHOICES, null=True, blank=True)

    def __str__(self):
        return f'{self.id} - {self.category} - {self.attribute} ({self.units})'




class Attribute(models.Model):

    name = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.id} - {self.name}'


class SKUCategoryAttribute(models.Model):
    sku = models.ForeignKey('StockKeepingUnit', on_delete=models.CASCADE)
    category_attribute = models.ForeignKey('CategoryAttribute', on_delete=models.PROTECT)
    value = models.CharField(max_length=128)

    def __str__(self):
        return f'{self.id} - {self.sku.product.name} - {self.category_attribute.attribute.name} - {self.value} - {self.category_attribute.units}'


class Image(models.Model):
    image = models.ImageField(upload_to='uploads/project_images')
    preview = models.ImageField(upload_to='uploads/project_images/previews', blank=True, null=True)
    sku = models.ForeignKey('StockKeepingUnit', on_delete=models.CASCADE, blank=True, null=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        
        # preview_img = pil_image.open(self.preview.path)
        # x = preview_img.width
        # y = preview_img.height
        # ratio = x/y
        # min_dimension = 360

        # if x > y:
        #     output_size = (min_dimension * ratio, min_dimension)
        # else:
        #     output_size = (min_dimension, min_dimension * ratio)
            
        # preview_img.thumbnail(output_size)
        # preview_img.save(self.preview.path)


        main_img = pil_image.open(self.image.path)
        x = main_img.width
        y = main_img.height
        ratio = x/y
        max_dimension = 1280

        if x > y:
            output_size = (max_dimension, max_dimension / ratio)
        else:
            output_size = (max_dimension / ratio, max_dimension)
        
        main_img.thumbnail(output_size)
        main_img.save(self.image.path)



class FileUpload(DateTimeMixin, models.Model):
    file = models.FileField(upload_to='product_files', 
                            validators=[FileExtensionValidator(allowed_extensions=['csv'])])
    uploaded = models.BooleanField(default=False)

products/forms.py
from django import forms
from django.forms import inlineformset_factory

from .models import CategoryAttribute, Category

class CategoryAttributeForm(forms.ModelForm):
    class Meta():
        model = CategoryAttribute
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        self.fields['show_on_tile'].widget.attrs['class'] = 'form-check-input'
        self.fields['show_in_description'].widget.attrs['class'] = 'form-check-input'
        self.fields['filter_type'].widget.attrs['class'] = 'form-select'


CategoryAttributeFormSet = inlineformset_factory(Category, CategoryAttribute, form=CategoryAttributeForm, extra=0, can_delete=True)


class CategoryEditForm(forms.ModelForm):
    class Meta():
        model = Category
        fields = ['name', 'parent']


    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['name'].widget.attrs['class'] = 'form-control'
            self.fields['parent'].widget.attrs['class'] = 'form-select'

products/views.py
import csv

from django.shortcuts import render
from django.views import View
from django.views.generic import UpdateView
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.core.files.storage import default_storage

from .services import *
from .models import *
from .forms import *


class ProductsFilterView(View):
    def get(self, request):
        
        path = request.path

        query = get_query(request.build_absolute_uri())
        print('!!!', query)
        
        category_name = path.split('/')[-2]
        category = get_object_or_404(Category, name__iexact=category_name)
        sku_list_for_filters = StockKeepingUnit.objects.filter(product__in=Product.objects.filter(category=category))
        sku_lst = StockKeepingUnit.objects.filter(query, product__in=Product.objects.filter(category=category))

        print('!', sku_lst)

        
        category_attrs = CategoryAttribute.objects.filter(Q(category=category) | Q (category=category.parent))
        
        # use sku_lst here to see only available filters
        filters = get_filters(category_attrs, sku_list_for_filters)
            
        context = {
            'sku_list': sku_lst,
            'category': category,
            'filters': filters,
        }
        
        return render(request, "products/products.html", context=context)

products/templates/products/__multi_filter.html
<div class='js-filter js-filter-multi' style="width:70%; margin: 0 0 30px 20px" id="filter-{{category_id}}" value="">
    <div style="font-weight:600; margin-bottom:10px;">{{category_attr}} {% if units %}({{units}}){% endif %}</div>
    {% for value in values %}
        <div style="display:flex; gap:20px; margin-bottom:5px">    
            <input class='form-check-input' style='margin:auto 0 auto 0; font-size:1.4rem' id='{{forloop.counter}}-{{category_attr|slugify}}' type="checkbox" value="{{value.value}}">
            <label class='form-check-label' style='margin:auto 0 auto 0;' for='{{forloop.counter}}-{{category_attr|slugify}}'>{{value.value}}</label>
        </div>
    {% endfor %}
</div>

products/templates/products/__range_filter.html
<div class='js-filter js-filter-range' style="width:70%; margin: 0 0 30px 20px" id="filter-{{category_id}}" value="">
<div style="font-weight:600">{{category_attr}}{{units.units}} {% if units %}({{units}}){% endif %}</div>
    <div style="display:flex; gap:40px">    
        <input class='js-filter-min form-control' type="text" placeholder="{{min.value}}">
        <input class='js-filter-max form-control' type="text" placeholder="{{max.value}}">
    </div>
</div>

products/templates/products/__single_filter.html
<div class='js-filter js-filter-single' style="width:70%; margin: 0 0 30px 20px" id="filter-{{category_id}}" value="">
    <div style="font-weight:600; margin-bottom:10px;">{{category_attr}} {% if units %}({{units}}){% endif %}</div>

    <select class="form-select" aria-label="{{category_attr|slugify}}-select">
            <option value="">---choices---</option>
        {% for value in values %}
            <option value="{{value.value}}">{{value.value}}</option>
        {% endfor %}
      </select>


</div>

products/templates/products/_tile.html
{% load extra_tags %}

<div class='tile'>
    <div style="display:flex; flex-direction:column">
        {% for image in sku.image_set.all %}
            <div ><img src='{{image.image.url}}'style="width:220px; height:220px; border-radius:20px; object-fit: cover;"></div>
        {% endfor %}
    </div>
    <div style="display:flex; flex-direction:column; gap:10px; max-width: 350px;">
        <div>{{sku.product.name}}</div>
        {% if sku.product.short_desc %}<div>{{sku.product.short_desc}}</div>{% endif %}
        <div style="display:flex; flex-direction:column">
            
            {% for attr in sku.skucategoryattribute_set.all %}
                <div style="font-size:0.9rem"><span style="font-weight:bold; font-size:0.9rem">{{attr.category_attribute.attribute.name}}:</span> {{attr.value}} {{attr.category_attribute.attribute.units}}</div>
            {% endfor %}
        </div>
    </div>

    <div style="display:flex; flex-direction:column; gap:10px">
        <div>${{sku.price}}</div>
        <button class="btn btn-primary">Buy now</button>
        <div>Delivery: on {{ 2|from_today:'%b %d' }}</div>
    </div>
</div>

products/templates/products/file_upload.html
hey

products/templates/products/maps.html
{% load static %}

<div id="map-test" class="map" style="width:1000px; height:500px;"></div>

<script src="https://api-maps.yandex.ru/2.1/?apikey=ваш API-ключ&lang=ru_RU"></script>
<script src="{% static '/js/maps.js' %}"></script>

products/templates/products/products.html
{% extends '_base.html' %}
{% load static %}
    
{% block content %}

    <div style="display:flex; gap:1px; min-height:100vh">
        {% include '_sidebar_filters.html' %}
        {% include '_main.html' %}
    </div>

    
    <script src="{% static '/js/search.js' %}"></script>

{% endblock %}