adminpanel/urls.py
from django.urls import path, re_path

from .views import *

urlpatterns = [
    re_path(r'edit-category', CategoryEditView.as_view(), name='edit-category'),
    path('file-upload', ImportFileDataView.as_view(), name='file-upload')
    ]

myshop/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static

from users.views import MyAccountSignupView
from .views import *


urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include(('products.urls', 'products'), namespace='products')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('accounts/signup/', MyAccountSignupView.as_view(), name='account-signup'),
    re_path(r'^accounts/', include('allauth.urls')),
    path('', IndexView.as_view(), name='index'),
    path('admin-panel/', include(('adminpanel.urls', 'adminpanel'), namespace='adminpanel')),
    path('maps/', MapsView.as_view(), name='maps'),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path, re_path
from django.views.generic import TemplateView
from django.contrib.auth.views import *
from .views import *



urlpatterns = [
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login-validation/', LoginValidationView.as_view(), name='login-validation'),
    path('registration-validation/', RegistrationValidationView.as_view(), name='registration-validation'),
    path('login/', MyLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),


    path('confirm-email/', TemplateView.as_view(template_name='registration/confirm_email.html'), name='confirm-email'), # user will see this page after registration
    path('email-verification/<uidb64>/<token>', EmailVerificationView.as_view(), name='email-verification'), #link that user gets in email
    path('invalid_email', TemplateView.as_view(template_name='registration/invalid_email.html'), name='invalid-email'),

    path('admin-panel/', AdminPanelView.as_view(), name='admin-panel'),
]

adminpanel/models.py
from django.db import models

# Create your models here.

adminpanel/forms.py
from django import forms
from django.forms import inlineformset_factory

from products.models import CategoryAttribute, Category


class CategoryAttributeForm(forms.ModelForm):
    class Meta():
        model = CategoryAttribute
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})
        self.fields['show_on_tile'].widget.attrs['class'] = 'form-check-input'
        self.fields['show_in_description'].widget.attrs['class'] = 'form-check-input'
        self.fields['filter_type'].widget.attrs['class'] = 'form-select'


CategoryAttributeFormSet = inlineformset_factory(Category, CategoryAttribute, form=CategoryAttributeForm, extra=0, can_delete=True)


class CategoryEditForm(forms.ModelForm):
    class Meta():
        model = Category
        fields = ['name', 'parent']


    def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.fields['name'].widget.attrs['class'] = 'form-control'
            self.fields['parent'].widget.attrs['class'] = 'form-select'

adminpanel/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import UpdateView
from django.shortcuts import get_object_or_404

from products.models import Category, FileUpload
from .forms import *

class CategoryEditView(UpdateView):

    model = Category
    template_name = 'adminpanel/admin_edit_category.html'
    form_class = CategoryEditForm

    
    def get_object(self, queryset=None):
        path = self.request.path
        
        category_name = path.split('/')[-2]
        category = get_object_or_404(Category, name__iexact=category_name)
        return category

    def get_success_url(self):
        return self.request.path
 
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        

        # passing user job experiences
        if self.request.POST:
            context['category_attrs_forms'] = CategoryAttributeFormSet(self.request.POST, instance=self.object)
            context['category_attrs_forms'].full_clean()
        else:
            context['category_attrs_forms'] = CategoryAttributeFormSet(instance=self.object)
          
        return context

    
    def form_valid(self, form):
        print('! here')
        context = self.get_context_data(form=form)

        formset = context['category_attrs_forms']
        print('!', formset.errors)

        if formset.is_valid():
            print('! form is valid')
            formset.instance = self.object
            formset.save()
            return super().form_valid(form)
        else:
            print('! form is not valid')
            return super().form_invalid(form)


class ImportFileDataView(View):
    def get(self, request):
        file = FileUpload.objects.last()
        print('!', file)
        # f = default_storage.open(os.path.join('Data_Files', new_file), 'r')
        # data = f.read()
        # f.close()
        # print(data)

        return render(request, 'products/file_upload.html')

adminpanel/templates/adminpanel/_admin_main.html
<div style="width:80%; background-color:white">
    <form method="POST" enctype="multipart/form-data" style="margin-bottom:50px">
        {% csrf_token %}
        <div style="margin:30px">
            {{form.as_p}}
        </div>
        <div style="display: grid; grid-template-columns: repeat(4, 1fr);grid-column-gap: 10px; grid-row-gap: 10px;">
            {{ category_attrs_forms.management_form }}
            {% for form in category_attrs_forms %}

                <div style="padding:30px">{{ form.as_p }}</div>
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            {% endfor %}
        </div>
        <div style="width:100%; padding:30px">
            <button class="btn btn-primary" style="width:100%">Submit</button>
        </div>
    </form>
</div>

adminpanel/templates/adminpanel/_admin_sidebar.html
<div class="sidebar">

    <div class="category-tree">
        {% load mptt_tags %}
        
        {% drilldown_tree_for_node category as drilldown count products.product.category in game_count %}
        {% for node,structure in drilldown|tree_info %}
            {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
            {% if node == category %}
                <strong>{{ node.name }}</strong> 
            {% else %}
                <a href='{% url "adminpanel:edit-category" %}{{ node.path }}'>{{ node.name }}</a>
                {% if node.parent_id == category.pk %}({{ node.game_count }}){% endif %}
                <!-- ({{node.game_count}}) -->
            {% endif %}
            {% for level in structure.closed_levels %}</li></ul>{% endfor %}
        {% endfor %}  
            
    </div>

</div>

adminpanel/templates/adminpanel/admin_edit_category.html
{% extends '_base.html' %}

{% block content %}

<div style="display:flex; gap:1px; min-height:100vh">
    {% include 'adminpanel/_admin_sidebar.html' %}
    {% include 'adminpanel/_admin_main.html' %}
</div>

{% endblock %}

adminpanel/templates/adminpanel/admin_panel.html
{% extends '_base.html' %}

{% block content %}

<div style="display:flex; gap:1px; min-height:100vh">
    {% include 'adminpanel/_admin_sidebar.html' %}
</div>

{% endblock %}